<?php

$title = 'Simple send mail';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php

echo $this->Partial('partial/flashMessages.phtml');

$form->setAttribute('action', $this->url('home', array('action' => 'index')));
$form->prepare();

echo $this->form()->openTag($form);

foreach ($form as $element) :
?>
    <div class="form-group">
        <label   for="<?php echo $element->getAttribute('name'); ?>" class="col-sm-2 control-label"><?php echo $element->getLabel() ?></label>
            <div class="col-sm-10">
                <?php
                    echo $this->formElement($element);
                ?>
            </div>
    </div>
<?php
endforeach;

echo $this->form()->closeTag();